version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.1.27
    container_name: ollama
    # ports: ["11434:11434"]
    volumes:
      - ./ollama_models/:/root/.ollama
    pull_policy: if_not_present
    restart: unless-stopped

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports: ["3000:8080"]
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    restart: unless-stopped

  genai:
    depends_on:
      ollama:
        condition: service_healthy
    container_name: "genai"
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8086:8086"]
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'


volumes:
  ollama-webui: {}
