version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.1.27
    container_name: ollama
    # ports: ["11434:11434"]
    volumes:
      - ./ollama_models/:/root/.ollama
    pull_policy: if_not_present
    restart: unless-stopped
    cpus: 1 # Limit to 50% of a CPU
    mem_limit: 8000m # Limit to 8GB of RAM

  backend:
    depends_on:
      ollama:
        condition: service_healthy
    container_name: "backend"
    build:
      context: backend
      dockerfile: Dockerfile
    ports: ["8086:8086"]
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'

  frontend:
    # depends_on:
    #   backend:
    #     condition: service_healthy
    container_name: "frontend"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports: ["3000:80"]
    environment:
      - 'REACT_APP_BACKEND_API_URL=http://backend:8086/api/generate'

# volumes:
#   frontend: {}